export const MISweek8 = [
    {
        id: 1,
        question: "Which of the following is TRUE regarding E-commerce and E-Business?",
        options: {
            a: "I, II, and III.",
            b: "I, II, and IV.",
            c: "I and III.",
            d: "All of these.",
        },
        answer: "All of these."
    },
    {
        id: 2,
        question: "Which of the following is not an example of information density on the Amazon website?",
        options: {
            a: "Online reviews",
            b: "Product images generated by the seller.",
            c: "Number of items sold.",
            d: "Product images generated by the customers.",
        },
        answer: "Number of items sold."
    },
    {
        id: 3,
        question: "Which of the following is FALSE in the context of personalization and customization on E-commerce websites?",
        options: {
            a: "Personalization is about tailoring an experience for the user.",
            b: "Personalization relies on data generated by user choice.",
            c: "Customization is about giving the user control over their experience.",
            d: "Personalization involves effort from users.",
        },
        answer: "Personalization involves effort from users."
    },
    {
        id: 4,
        question: "Which of the following is FALSE in the context of an e-commerce website?",
        options: {
            a: "The network effect on e-commerce websites is a phenomenon whereby increased numbers of people (buyers/sellers) improve the value of a good or service.",
            b: "Hit-and-run pricing is also known as dynamic pricing of the product.",
            c: "Order tracking on an e-commerce platform is an example of Interactivity with the website.",
            d: "Order tracking on an e-commerce platform is an example of the ubiquity of the website.",
        },
        answer: "Order tracking on an e-commerce platform is an example of Interactivity with the website."
    },
    {
        id: 5,
        question: "Which parameters are considered for ranking a country for the e-commerce market? [ I => The average revenue per shopper, II => The number of products listed on the website, III => The percentage of the population selling online, IV => The percentage of the population shopping online. ]",
        options: {
            a: "I, II, and III.",
            b: "I, III, and IV.",
            c: "I and II.",
            d: "I and IV.",
        },
        answer: "I and IV."
    },
    {
        id: 6,
        question: "Which of the following are the challenges of shopping on e-commerce websites?",
        options: {
            a: "Trust issues among sellers and buyers",
            b: "Data security issues.",
            c: "Legal and ethical issues about data sharing.",
            d: "The availability of product alternatives.",
        },
        answer: "Trust issues among sellers and buyers"
    },
    {
        id: 7,
        question: "Which of the following is not a key element of a business model?",
        options: {
            a: "Value proposition.",
            b: "Competitive advantage.",
            c: "Market strategy",
            d: "Universal standards",
        },
        answer: "Universal standards"
    },
    {
        id: 8,
        question: "The primary source of revenue in a subscription revenue model is",
        options: {
            a: "Fees from advertisers in exchange for advertisements.",
            b: "Fees for business referrals.",
            c: "Fees from subscribers in exchange for access to content or services.",
            d: "Fees for enabling or executing a transaction.",
        },
        answer: "Fees from subscribers in exchange for access to content or services."
    },
    {
        id: 9,
        question: "Which of the following is an example of the affiliate revenue model on an e-commerce website?",
        options: {
            a: "The fees charged from advertisers in exchange for advertisements.",
            b: "The fees charged from subscribers in exchange for access to content or service.",
            c: "The money offered for the business referrals.",
            d: "The volume of sales of goods or services.",
        },
        answer: "The money offered for the business referrals."
    },
    {
        id: 10,
        question: "Which of the following is not a primary B2C business model?",
        options: {
            a: "Content provider",
            b: "Industry conglomerate.",
            c: "Transaction broker.",
            d: "Service provider.",
        },
        answer: "Industry conglomerate."
    },
];
